-- Run this in Supabase SQL Editor to fix product insertion

-- Drop and recreate products table with fresh policies
DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    image TEXT,
    image_url TEXT,
    category TEXT NOT NULL,
    fabric TEXT,
    length TEXT,
    care TEXT,
    description TEXT,
    in_stock BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Allow all operations for everyone
DROP POLICY IF EXISTS " Allow all products" ON products;
CREATE POLICY "allow_all_products" ON products FOR ALL USING (true) WITH CHECK (true);

-- Also fix storage bucket policies
DROP POLICY IF EXISTS "Public read product images" ON storage.objects;
DROP POLICY IF EXISTS "Auth upload product images" ON storage.objects;

CREATE POLICY "Public read product images" ON storage.objects 
    FOR SELECT USING (bucket_id = 'product-images');

CREATE POLICY "Anyone upload product images" ON storage.objects 
    FOR INSERT WITH CHECK (bucket_id = 'product-images');

CREATE POLICY "Anyone update product images" ON storage.objects 
    FOR UPDATE USING (bucket_id = 'product-images');

CREATE POLICY "Anyone delete product images" ON storage.objects 
    FOR DELETE USING (bucket_id = 'product-images');
