-- ============================================
-- ALIZA E-COMMERCE SUPABASE SCHEMA
-- Run in Supabase SQL Editor
-- ============================================

-- Drop existing tables
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS products CASCADE;

-- Create products table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    image TEXT,
    image_url TEXT,
    category TEXT NOT NULL,
    fabric TEXT,
    length TEXT,
    care TEXT,
    description TEXT,
    in_stock BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create reviews table
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create orders table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_address TEXT NOT NULL,
    customer_city TEXT NOT NULL,
    items JSONB NOT NULL,
    total NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'delivered', 'not_delivered')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Products: Allow ALL operations for everyone
DROP POLICY IF EXISTS "allow_all_products" ON products;
CREATE POLICY "allow_all_products" ON products FOR ALL USING (true) WITH CHECK (true);

-- Reviews: Allow ALL operations for everyone
DROP POLICY IF EXISTS "allow_all_reviews" ON reviews;
CREATE POLICY "allow_all_reviews" ON reviews FOR ALL USING (true) WITH CHECK (true);

-- Orders: Allow ALL operations for everyone
DROP POLICY IF EXISTS "allow_all_orders" ON orders;
CREATE POLICY "allow_all_orders" ON orders FOR ALL USING (true) WITH CHECK (true);

-- Storage policies
DROP POLICY IF EXISTS "Public read product images" ON storage.objects;
DROP POLICY IF EXISTS "Auth upload product images" ON storage.objects;

CREATE POLICY "Public read product images" ON storage.objects 
    FOR SELECT USING (bucket_id = 'product-images');

CREATE POLICY "Anyone upload product images" ON storage.objects 
    FOR INSERT WITH CHECK (bucket_id = 'product-images');

CREATE POLICY "Anyone update product images" ON storage.objects 
    FOR UPDATE USING (bucket_id = 'product-images');

CREATE POLICY "Anyone delete product images" ON storage.objects 
    FOR DELETE USING (bucket_id = 'product-images');
