export const products = [
  {
    id: 1,
    name: "Embroidered Royal Blue Lawn Suit",
    price: "Rs. 4,500",
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=400&q=60&fm=webp",
    category: "Women",
    fabric: "Pure Cotton Lawn",
    length: "6 meters",
    care: "Hand wash recommended",
    description: "Beautiful embroidered lawn suit with intricate thread work. Perfect for summer occasions and casual gatherings. Features a coordinated dupatta and shirt.",
    inStock: true,
  },
  {
    id: 2,
    name: "Classic White Cotton Shalwar Kameez",
    price: "Rs. 3,200",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=60&fm=webp",
    category: "Men",
    fabric: "100% Premium Cotton",
    length: "5.5 meters",
    care: "Machine washable",
    description: "Timeless white shalwar kameez crafted from premium quality cotton. Regular fit design suitable for both formal and casual occasions.",
    inStock: true,
  },
  {
    id: 3,
    name: "Floral Pink Chiffon Dress",
    price: "Rs. 5,800",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=400&q=60&fm=webp",
    category: "Women",
    fabric: "Premium Chiffon",
    length: "4 meters",
    care: "Dry clean only",
    description: "Elegant floral chiffon dress with beautiful prints. Lightweight and perfect for weddings and formal events. Comes with lining.",
    inStock: true,
  },
  {
    id: 4,
    name: "Kids Colorful Frock Set",
    price: "Rs. 2,500",
    image: "https://images.unsplash.com/photo-1519235106638-35e35556b40d?auto=format&fit=crop&w=400&q=60&fm=webp",
    category: "Kids",
    fabric: "Soft Cotton Blend",
    length: "2.5 meters",
    care: "Machine washable",
    description: "Adorable colorful frock set for kids. Made from soft, skin-friendly fabric. Available in multiple vibrant colors.",
    inStock: true,
  },
  {
    id: 5,
    name: "Luxury Gold Silk Ensemble",
    price: "Rs. 12,500",
    image: "https://images.unsplash.com/photo-1569407228235-9a744849a066?auto=format&fit=crop&w=400&q=60&fm=webp",
    category: "Women",
    fabric: "Pure Silk",
    length: "6.5 meters",
    care: "Professional dry clean",
    description: "Exquisite gold silk ensemble with heavy embellishments. Perfect for weddings and grand celebrations. Includes heavy dupatta with border work.",
    inStock: true,
  },
  {
    id: 6,
    name: "Traditional Black Sherwani",
    price: "Rs. 8,500",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=400&q=60&fm=webp",
    category: "Men",
    fabric: "Silk Blend",
    length: "4 meters",
    care: "Dry clean recommended",
    description: "Classic black sherwani with elegant embroidery. Perfect for groom and wedding guests. Features traditional cut with modern styling.",
    inStock: true,
  },
  {
    id: 7,
    name: "Pastel Green Cambric Suit",
    price: "Rs. 3,800",
    image: "https://images.unsplash.com/photo-1618932260643-2b6726551715?auto=format&fit=crop&w=400&q=60&fm=webp",
    category: "Women",
    fabric: "Premium Cambric",
    length: "5.5 meters",
    care: "Hand wash recommended",
    description: "Fresh pastel green cambric suit with minimalistic prints. Ideal for office wear and daytime events. Breathable fabric for all-day comfort.",
    inStock: true,
  },
  {
    id: 8,
    name: "Festive Ready-to-Wear Dress",
    price: "Rs. 6,200",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=400&q=60&fm=webp",
    category: "Women",
    fabric: "Jacquard Blend",
    length: "4.5 meters",
    care: "Dry clean only",
    description: "Beautiful festive dress ready to wear. Features intricate embellishments and premium quality fabric. Perfect for Eid and celebrations.",
    inStock: true,
  },
];

export const categories = [
  { id: 1, name: "Women", image: "https://images.unsplash.com/photo-1558171813-4c088753af8f?auto=format&fit=crop&w=400&q=60&fm=webp" },
  { id: 2, name: "Men", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=60&fm=webp" },
  { id: 3, name: "Kids", image: "https://images.unsplash.com/photo-1519235106638-35e35556b40d?auto=format&fit=crop&w=400&q=60&fm=webp" },
];
